import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const APS_ACCESS_TOKEN = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjY0RE9XMnJoOE9tbjNpdk1NU0xlNGQ2VHEwUV9SUzI1NiIsInBpLmF0bSI6Ijd6M2gifQ.eyJzY29wZSI6WyJjb2RlOmFsbCIsImRhdGE6d3JpdGUiLCJkYXRhOnJlYWQiLCJidWNrZXQ6Y3JlYXRlIiwiYnVja2V0OmRlbGV0ZSIsImJ1Y2tldDpyZWFkIl0sImNsaWVudF9pZCI6InhsenJ3UFphbFpzQVZUR0h2YkViYTNmQUFoZG5DQ0t2IiwiYXVkIjoiaHR0cHM6Ly9hdXRvZGVzay5jb20vYXVkL2Fqd3RleHA2MCIsImp0aSI6InFjV25FRVROUEFDZXQzTmVnU0VMZUtKTEJJQlhMbnZaakdJdGZjdDFoUU8zS1F2ZGE2RXB6WHREcG1MWnBaVnYiLCJleHAiOjE3MTE1OTEwODF9.czQAO7N9HS93Pqye4nowi4N-6pUTcAnFrrvKyqBGV2GoAVzRWxz89EhJcjD_64I85ufW_uhAb27MzYTtkPdPAX_aMClzX833uLnQRaFbnEas_SCLAQOMvE6PI_hkci9Yb8Qgr9ghg4GWSH25krZTtldXPOvauQ9kUj_ppGIG3ADNgekrJuwZf30xwJidP3YAKKnwvQuOM_vjR6fE9R_8AcVt2ppf3qr7SF15NCVH-dGNWHHxSkd9FZv3DHUxX9N5kHTnKy11YFA7Rzyqhkm-ONBEUz0v67AVTR6sgbUOcCQJ2tS1WlarjoQEc6UpubnA95sPLWMsyW6fS4H2sAN3Qw"
const APS_MODEL_URN = 'dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6ZGV2X2JpbV9tb2RlbF9mb2xkZXJfMTM4MzQxNDAzNzc4MDcyNTc3L09pbCUyMFNraW1taW5nJTIwVmVzc2VsLm53ZA'; // Specify your model URN

const root = ReactDOM.createRoot(document.getElementById('root'));
if (!APS_ACCESS_TOKEN || !APS_MODEL_URN) {
    root.render(<div>Please specify <code>APS_ACCESS_TOKEN</code> and <code>APS_MODEL_URN</code> in the source code.</div>);
} else {
    root.render(<App token={APS_ACCESS_TOKEN} urn={APS_MODEL_URN} />);
}
